//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyfirstMvcapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactID { get; set; }
        public string ContactName { get; set; }
        public string ContactEmailID { get; set; }
        public string ContactMessage { get; set; }
        public System.DateTime ContactDate { get; set; }
    }
}
